version: '3.8'

services:
  backend:
    build: ./back
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/al-nasser-school
      - JWT_SECRET=your-jwt-secret
      - JWT_REFRESH_SECRET=your-jwt-refresh-secret
    depends_on:
      - mongodb
    networks:
      - app-network
    command: npm start

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
