# Use an official Node.js runtime as a parent image
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Make port 3000 available
EXPOSE 3000

# Define the command to run the dev server
CMD [ "npm", "run", "dev" ]
